Fix some issues that were found in testing environment
companieshouse/third-party-test-harness pull request #10
Opened 2021-01-28 14:04 UTC by Ngriffiths1

Added some logging for potential errors, changed html to only display relevant fields and give more of an explanation when requested functional scopes

2021-01-28 18:03 UTC, rafahop requested changes
Do we really want those new debug log lines? I thought they were there for your own local debugging but if we really want some logging we should make it meaningful and definitely not log any sensitive data (and the access token is very sensitive)

2021-01-28 18:03 UTC, rafahop commented on README.md
> +* Whilst using this app it is only configured to work with HTTP
I think this depends on how the server where the app is running is configured so probably not something to be in the readme

2021-01-28 18:03 UTC, rafahop commented on src/main/resources/templates/loginRequestedScope.html
> +        <p class="lead">Enter the requested scopes you wish to obtain. To file with Companies House you must also obtain the user_profile : read scope.
`user_profile : read` is a permission, not a scope. Should we refer to a valid scope instead?

Would it be a good idea prepopulating the scope input field with that value?

What happens if the user does not enter that scope? Should we handle that scenario?

2021-01-29 07:29 UTC, Ngriffiths1 commented on README.md
> +* Whilst using this app it is only configured to work with HTTP
Billy wanted me to put a line in the readme to say that the app in configured to work over HTTP, if you have a better suggestion for the information i can put that in instead?

2021-01-29 17:13 UTC, Ngriffiths1 commented on src/main/resources/templates/loginRequestedScope.html
> +        <p class="lead">Enter the requested scopes you wish to obtain. To file with Companies House you must also obtain the user_profile : read scope.
Changed the text to be more accurate and prepopulated the text area with the relevant scope. If they do not enter that scope then they haven't read the text area correctly.

2021-01-29 17:13 UTC, Ngriffiths1 commented on README.md
> +* Whilst using this app it is only configured to work with HTTP
Put a more accurate message in and removed the CHS line

2021-01-29 17:52 UTC, rafahop approved these changes

2021-02-01 08:21 UTC, merged

2024-05-27 00:47 UTC, arslan-raza-143 commented
b011ae64efd88d24be0a0542abfbb934521faca3